package EventManagement;


/**
* EventManagement/managerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EventManagement.idl
* Tuesday, June 11, 2019 8:54:04 PM EDT
*/

public interface managerInterface extends managerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface managerInterface
