package EventManagement;


/**
* EventManagement/managerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EventManagement.idl
* Thursday, June 27, 2019 3:13:50 PM EDT
*/

public interface managerInterface extends managerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface managerInterface
