package EventManagement;


/**
* EventManagement/managerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EventManagement.idl
* Sunday, July 7, 2019 1:17:15 PM EDT
*/

public interface managerInterface extends managerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface managerInterface
