package FrontEnd;


/**
* FrontEnd/frontEndInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Sunday, July 14, 2019 6:12:50 PM EDT
*/

abstract public class frontEndInterfaceHelper
{
  private static String  _id = "IDL:FrontEnd/frontEndInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, FrontEnd.frontEndInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FrontEnd.frontEndInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FrontEnd.frontEndInterfaceHelper.id (), "frontEndInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FrontEnd.frontEndInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_frontEndInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FrontEnd.frontEndInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FrontEnd.frontEndInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FrontEnd.frontEndInterface)
      return (FrontEnd.frontEndInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FrontEnd._frontEndInterfaceStub stub = new FrontEnd._frontEndInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FrontEnd.frontEndInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FrontEnd.frontEndInterface)
      return (FrontEnd.frontEndInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FrontEnd._frontEndInterfaceStub stub = new FrontEnd._frontEndInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
