package FrontEnd;

/**
* FrontEnd/frontEndInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Sunday, July 14, 2019 6:12:50 PM EDT
*/

public final class frontEndInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public FrontEnd.frontEndInterface value = null;

  public frontEndInterfaceHolder ()
  {
  }

  public frontEndInterfaceHolder (FrontEnd.frontEndInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FrontEnd.frontEndInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FrontEnd.frontEndInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FrontEnd.frontEndInterfaceHelper.type ();
  }

}
