package FrontEnd;


/**
* FrontEnd/frontEndInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Sunday, July 14, 2019 6:12:50 PM EDT
*/

public interface frontEndInterface extends frontEndInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface frontEndInterface
