package FrontEnd;


/**
* FrontEnd/frontEndInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Sunday, July 14, 2019 6:12:50 PM EDT
*/

public interface frontEndInterfaceOperations 
{
  String addEvent (String managerId, String eventId, String eventType, String eventCapacity);
  String removeEvent (String managerId, String eventId, String eventType);
  String listEventAvailability (String managerId, String eventType);
  String eventBooking (String customerId, String eventId, String eventType);
  String cancelBooking (String customerId, String eventId, String eventType);
  String getBookingSchedule (String customerId);
  String swapEvent (String customerId, String newEventId, String newEventType, String oldEventId, String oldEventType);
} // interface frontEndInterfaceOperations
